#!/bin/bash

set -e

if [ $# -gt 0 ]; then # we have args
    filename=$1
else # we have no args
    filename='spec/controllers spec/permissions spec/models spec/lib spec/presenters spec/requests spec/services spec/script'
fi

command="ruby -S bundle exec rspec"
if [ "$JENKINS_HOME" != "" ]; then
    command="$command --options .rspec-ci"
fi

args=("$@")
test "$RAILS_ENV" = "" && RAILS_ENV=test
RAILS_ENV=$RAILS_ENV $command $filename ${args[@]:1:100}
