#!/bin/bash

set -e

if [ $# -gt 0 ]; then # we have args
    filename=$1
else # we have no args
    filename='spec/controllers spec/permissions spec/models spec/lib spec/presenters spec/requests spec/services'
fi

command="ruby -S bundle exec rspec"

args=("$@")
RAILS_ENV=test $command $filename ${args[@]:1:100}
